export const SETTING_KEYS = {
  siteTitle: "site_title",
  homepageTitle: "homepage_title",
  homepageDescription: "homepage_description",
  defaultOgTitle: "default_og_title",
  defaultOgDescription: "default_og_description",
  organizationName: "organization_name",
  contactEmail: "contact_email",
  googleSearchConsole: "google_search_console",
  bingVerification: "bing_verification",
  googleAnalyticsId: "google_analytics_id",
  microsoftClarityId: "microsoft_clarity_id",
  canonicalDomain: "canonical_domain",
  heroEyebrow: "hero_eyebrow",
  heroTitle: "hero_title",
  heroSubtitle: "hero_subtitle",
  primaryCtaLabel: "primary_cta_label",
  primaryCtaHref: "primary_cta_href",
  secondaryCtaLabel: "secondary_cta_label",
  secondaryCtaHref: "secondary_cta_href",
  featuredCountrySlugs: "featured_country_slugs",
  featuredVisaSlugs: "featured_visa_slugs",
  featuredComparisonPairs: "featured_comparison_pairs",
  featuredGuideSlugs: "featured_guide_slugs",
  homepageFaqs: "homepage_faqs",
  bottomCtaTitle: "bottom_cta_title",
  bottomCtaDescription: "bottom_cta_description",
} as const;

export type SettingKey = (typeof SETTING_KEYS)[keyof typeof SETTING_KEYS];
